---
title: "Data_Wrangling"
output: pdf_document
---

## Set up

```{r setup, message=FALSE}
knitr::opts_chunk$set(include = FALSE) # don't show output and the code 

library(tidyverse)
library(here)
library(lubridate)


Database <- read.csv(here("Raw/ROSIE/Database.csv"), stringsAsFactors = TRUE)
```

## Data Wrangling

```{r data wrangling}
cleaned_data <- Database %>% 
  filter(is.na(Chemical_Concentration)) %>% # don't want chemical treatment
  filter(!is.na(Proportion_Male)) %>% # we want to rows that have proportion_male data
  filter(SDM == 'TSD') %>% # we want to focus on turtles that are TSD
  select(Order, Family, Genus, Species, 
         Mean_Temp,Mean_Temp_SD, 
         Latitude, Longitude, Captive, Humidity, 
         First_Year, First_Month, Last_Year, Last_Month,
         Proportion_Male, Proportion_Female) 
  # the term "sex-ratio" is misleading -> abondon, just use male proportion
  #mutate(Sex_ratio = Proportion_Male / Proportion_Female) %>% 
 # mutate(Sex_ratio = ifelse(is.infinite(Sex_ratio), 1, Sex_ratio)) %>% # 0/1 -> 0 - all female, 1 -> female = male, 1/0 -> infinite -> all male
  # filter(!is.nan(Sex_ratio)) # we found there are some NaN and infinite data in sex ratio column, we may need to filter these data out  

# Deal with date
cleaned_data$Start_Date <- as.Date(paste(cleaned_data$First_Year, 
                                         cleaned_data$First_Month,
                                         "01", sep = "-"))
cleaned_data$End_Date <- as.Date(paste(cleaned_data$Last_Year, 
                                         cleaned_data$Last_Month,
                                         "01", sep = "-"))

# re-select column we need
cleaned_data <- select(cleaned_data, Order, Family, Genus, Species,
                       Mean_Temp,Mean_Temp_SD,
                       Latitude, Longitude, Captive, Humidity, 
                       Start_Date, End_Date, Proportion_Male, Proportion_Female)

# create a cleaned data in processed folder
write.csv(cleaned_data, file = here("Processed/Cleaned_Data.csv"), row.names = FALSE)
```
